@startuml
left to right direction

rectangle reception{
(set clock details)
(reset clock balance)
(pay bill)
}

rectangle buy_something{
rectangle restaurant{
(buy food)
}
rectangle bar{
(buy alcohol)
(buy alcohol free drink)
}
}

rectangle use_services{
rectangle welness{
(use sauna)
(use swimmingpool)
}
}

:receptionist:-->(set clock details)
:receptionist:-->(reset clock balance)
:adult:-->buy_something
:adult:-->use_services
:adult:-->(pay bill)
(buy alcohol)<..:kid::forbidden
(use sauna)<..:kid::forbidden
buy_something<--:kid:
use_services<--:kid:
@enduml
